### PR TITLE
Simplify auth lookups.

### PR DESCRIPTION
**Pull request by mrstegeman**

### CODE REVIEW

**Comment by mrstegeman** [comment]
@MarcGraham Can you confirm that this still works for you with your JWT devices?

@madb1lly Does this improve anything for you?

**Comment by MarcGraham** [comment]
@mrstegeman 

This looks to be working fine for me. Thanks.

**Comment by typh289** [comment]
I get this error on logs after addon update
ERROR  : thing-url-adapter: TypeError: Cannot read property 'replace' of undefined
ERROR  : thing-url-adapter:     at ThingURLAdapter.loadThing (/etc/webthings-gateway/addons/thing-url-adapter/thing-url-adapter.js:549:27)

**Comment by mrstegeman** [comment]
v0.5.2 should fix the issue.

**Comment by typh289** [comment]
yes fixed, thank you!

**Comment by MarcGraham** [comment]
@mrstegeman 

Hi -- feel free to ping me if I can help test this.

**Comment by MarcGraham** [comment]
Hi,
Looks like 5.2 breaks my jwt implementation. I'll see if I can find the issue.

**Pull request merged**
